INSERT INTO `eftech`.`users` (`username`, `password`, `enabled`) VALUES ('Admin', '1111', '1');
INSERT INTO `eftech`.`users` (`username`, `password`, `enabled`) VALUES ('Admin_info', '2222', '1');
INSERT INTO `eftech`.`users` (`username`, `password`, `enabled`) VALUES ('Admin_pict', '4444', '1');
INSERT INTO `eftech`.`users` (`username`, `password`, `enabled`) VALUES ('Admin_price', '3333', '1');

INSERT INTO `eftech`.`authorities` (`id`, `username`, `authority`) VALUES ('1', 'Admin', 'ROLE_ADMIN');
INSERT INTO `eftech`.`authorities` (`id`, `username`, `authority`) VALUES ('2', 'Admin_info', 'ROLE_USER_INFO');
INSERT INTO `eftech`.`authorities` (`id`, `username`, `authority`) VALUES ('3', 'Admin_price', 'ROLE_USER_PRICE');
INSERT INTO `eftech`.`authorities` (`id`, `username`, `authority`) VALUES ('4', 'Admin_pict', 'ROLE_USER_PICT');

INSERT INTO `eftech`.`email_recipient` (`id_email_recipient`, `email`) VALUES ('1', 'gon4arikvadim@gmail.com');

INSERT INTO `eftech`.`particle_board` (`Product_ID`, `Laminated`, `Thickness`, `Length`, `Weight`, `Price`, `Foto_1`, `Foto_2`, `Foto_3`, `Foto_4`, `Description_bench`) VALUES ('000001', '105', '15', '1250', '1250', '20', 'particleboard_1.jpg', 'particleboard_2.jpg', 'particleboard_3.jpg', 'particleboard_4.jpg', 'Equipment  Main drive <br>   Air conditioner for electrical cabinet <br>   Half cabin <br>   PROGRESSline & Planonlight <br>   Electronic handwheel <br>    Direct measuring system X,Y,Z <br>   Chip Removal Package <br>   Coolant-air blast-over <br>   Sandvik-Toolkit for SK 40 <br>   DMG Netservice - client <br>');
INSERT INTO `eftech`.`particle_board` (`Product_ID`, `Laminated`, `Thickness`, `Length`, `Weight`, `Price`, `Foto_1`, `Foto_2`, `Foto_3`, `Foto_4`, `Description_bench`) VALUES ('000002', '105', '15', '1250', '1250', '20', 'particleboard_1.jpg', 'particleboard_2.jpg', 'particleboard_3.jpg', 'particleboard_4.jpg', 'Equipment  Main drive <br>   Air conditioner for electrical cabinet <br>   Half cabin <br>   PROGRESSline & Planonlight <br>   Electronic handwheel <br>    Direct measuring system X,Y,Z <br>   Chip Removal Package <br>   Coolant-air blast-over <br>   Sandvik-Toolkit for SK 40 <br>   DMG Netservice - client <br>');
INSERT INTO `eftech`.`particle_board` (`Product_ID`, `Laminated`, `Thickness`, `Length`, `Weight`, `Price`, `Foto_1`, `Foto_2`, `Foto_3`, `Foto_4`, `Description_bench`) VALUES ('000003', '105', '15', '1250', '1250', '20', 'particleboard_1.jpg', 'particleboard_2.jpg', 'particleboard_3.jpg', 'particleboard_4.jpg', 'Equipment  Main drive <br>   Air conditioner for electrical cabinet <br>   Half cabin <br>   PROGRESSline & Planonlight <br>   Electronic handwheel <br>    Direct measuring system X,Y,Z <br>   Chip Removal Package <br>   Coolant-air blast-over <br>   Sandvik-Toolkit for SK 40 <br>   DMG Netservice - client <br>');
INSERT INTO `eftech`.`particle_board` (`Product_ID`, `Laminated`, `Thickness`, `Length`, `Weight`, `Price`, `Foto_1`, `Foto_2`, `Foto_3`, `Foto_4`, `Description_bench`) VALUES ('000004', '105', '15', '1250', '1250', '20', 'particleboard_1.jpg', 'particleboard_2.jpg', 'particleboard_3.jpg', 'particleboard_4.jpg', 'Equipment  Main drive <br>   Air conditioner for electrical cabinet <br>   Half cabin <br>   PROGRESSline & Planonlight <br>   Electronic handwheel <br>    Direct measuring system X,Y,Z <br>   Chip Removal Package <br>   Coolant-air blast-over <br>   Sandvik-Toolkit for SK 40 <br>   DMG Netservice - client <br>');
INSERT INTO `eftech`.`particle_board` (`Product_ID`, `Laminated`, `Thickness`, `Length`, `Weight`, `Price`, `Foto_1`, `Foto_2`, `Foto_3`, `Foto_4`, `Description_bench`) VALUES ('000005', '105', '15', '1250', '1250', '20', 'particleboard_1.jpg', 'particleboard_2.jpg', 'particleboard_3.jpg', 'particleboard_4.jpg', 'Equipment  Main drive <br>   Air conditioner for electrical cabinet <br>   Half cabin <br>   PROGRESSline & Planonlight <br>   Electronic handwheel <br>    Direct measuring system X,Y,Z <br>   Chip Removal Package <br>   Coolant-air blast-over <br>   Sandvik-Toolkit for SK 40 <br>   DMG Netservice - client <br>');

INSERT INTO `eftech`.`plywood` (`Product_ID`, `Water_resistance`, `Sanded_or_unsanded`, `Thickness`, `Length`, `Weight`, `Price`, `Foto_1`, `Foto_2`, `Foto_3`, `Foto_4`, `Description_bench`) VALUES ('065081', 'FK', 'sanded', '15', '1250', '1234', '20', 'plywood_1.jpg', 'plywood_2.jpg', 'plywood_3.jpg', 'plywood_4.jpg', 'Equipment  Main drive <br>Air conditioner for electrical cabinet <br>Half cabin <br>PROGRESSline & Planonlight <br>Electronic handwheel <br>Direct measuring system X,Y,Z <br>Chip Removal Package <br> Coolant-air blast-over <br>Sandvik-Toolkit for SK 40 <br>DMG Netservice - client <br>');
INSERT INTO `eftech`.`plywood` (`Product_ID`, `Water_resistance`, `Sanded_or_unsanded`, `Thickness`, `Length`, `Weight`, `Price`, `Foto_1`, `Foto_2`, `Foto_3`, `Foto_4`, `Description_bench`) VALUES ('065082', 'FK', 'sanded', '15', '1250', '1234', '20', 'plywood_1.jpg', 'plywood_2.jpg', 'plywood_3.jpg', 'plywood_4.jpg', 'Equipment  Main drive <br>Air conditioner for electrical cabinet <br>Half cabin <br>PROGRESSline & Planonlight <br>Electronic handwheel <br>Direct measuring system X,Y,Z <br>Chip Removal Package <br> Coolant-air blast-over <br>Sandvik-Toolkit for SK 40 <br>DMG Netservice - client <br>');
INSERT INTO `eftech`.`plywood` (`Product_ID`, `Water_resistance`, `Sanded_or_unsanded`, `Thickness`, `Length`, `Weight`, `Price`, `Foto_1`, `Foto_2`, `Foto_3`, `Foto_4`, `Description_bench`) VALUES ('065083', 'FK', 'sanded', '15', '1250', '1234', '20', 'plywood_1.jpg', 'plywood_2.jpg', 'plywood_3.jpg', 'plywood_4.jpg', 'Equipment  Main drive <br>Air conditioner for electrical cabinet <br>Half cabin <br>PROGRESSline & Planonlight <br>Electronic handwheel <br>Direct measuring system X,Y,Z <br>Chip Removal Package <br> Coolant-air blast-over <br>Sandvik-Toolkit for SK 40 <br>DMG Netservice - client <br>');
INSERT INTO `eftech`.`plywood` (`Product_ID`, `Water_resistance`, `Sanded_or_unsanded`, `Thickness`, `Length`, `Weight`, `Price`, `Foto_1`, `Foto_2`, `Foto_3`, `Foto_4`, `Description_bench`) VALUES ('065084', 'FK', 'sanded', '15', '1250', '1234', '20', 'plywood_1.jpg', 'plywood_2.jpg', 'plywood_3.jpg', 'plywood_4.jpg', 'Equipment  Main drive <br>Air conditioner for electrical cabinet <br>Half cabin <br>PROGRESSline & Planonlight <br>Electronic handwheel <br>Direct measuring system X,Y,Z <br>Chip Removal Package <br> Coolant-air blast-over <br>Sandvik-Toolkit for SK 40 <br>DMG Netservice - client <br>');
INSERT INTO `eftech`.`plywood` (`Product_ID`, `Water_resistance`, `Sanded_or_unsanded`, `Thickness`, `Length`, `Weight`, `Price`, `Foto_1`, `Foto_2`, `Foto_3`, `Foto_4`, `Description_bench`) VALUES ('065085', 'FK', 'sanded', '15', '1250', '1234', '20', 'plywood_1.jpg', 'plywood_2.jpg', 'plywood_3.jpg', 'plywood_4.jpg', 'Equipment  Main drive <br>Air conditioner for electrical cabinet <br>Half cabin <br>PROGRESSline & Planonlight <br>Electronic handwheel <br>Direct measuring system X,Y,Z <br>Chip Removal Package <br> Coolant-air blast-over <br>Sandvik-Toolkit for SK 40 <br>DMG Netservice - client <br>');
